### PR TITLE
Fix OpenStack events capability not being set

### LINKED ISSUE #925: AMQP credential verification does not set 'events' capability
## Summary

The `verify_credentials` method in `app/models/manageiq/providers/openstack/cloud_manager.rb` contains an early exit (`return ret unless auth_type.nil?`) that prevents the automatic setting of the **`capabilities["events"]`** flag when credentials are verified with an explicit `auth_type` (e.g., `:amqp` or `:default`).

This means the capability is only updated during the rare calls where **`auth_type` is `nil`**, while the explicit verification calls (which confirm AMQP connectivity) exit early, leaving the capability flag disabled and preventing the event catchers from starting automatically.

## Environment

  * **ManageIQ Version**: Radjabov-1 (and likely earlier/later versions using the same logic)
  * **OpenStack Version**: Any version with AMQP

-----

### Location

`app/models/manageiq/providers/openstack/cloud_manager.rb` $\rightarrow$ `verify_credentials`

### Current Code (BROKEN)

```ruby
def verify_credentials(auth_type = nil, options = {})
  options[:service] ||= "Compute"
  ret = super
  return ret unless auth_type.nil?  # ← EARLY EXIT HERE for auth_type != nil

  capabilities["events"] = !!event_monitor_available?  # ← This line is often skipped!
  save! if changed?
  true
end
```

### Log Evidence and Flow Analysis

The following log snippet clearly shows two failed attempts to update the capability where `auth_type` is *not* `nil`, followed by the original code's logic being bypassed.

| Timestamp | `auth_type` | Log Message | Analysis |
| :--- | :--- | :--- | :--- |
| `10:56:28` | `:default` | `✗ auth_type is NOT nil (default) - ORIGINAL CODE WOULD EXIT HERE!` | **Failure 1:** Called with `:default` (during initial save/validation). Original code exits before checking/setting capabilities. |
| `10:56:29` | `:amqp` | `✗ auth_type is NOT nil (amqp) - ORIGINAL CODE WOULD EXIT HERE!` | **Failure 2:** Called explicitly for AMQP endpoint verification. Original code exits before checking/setting capabilities. |

**Crux of the Issue:** The `event_monitor_available?` check, which determines if the capability should be set to `true`, is skipped whenever `auth_type` is `:amqp` or `:default`. These calls are the critical moments where connectivity is confirmed and the capability *should* be set.

### Impact

  * Event catchers (cloud\_manager, storage, network) **do not start** automatically.
  * Requires a manual Rails console workaround to enable events:
    ```ruby
    ems.capabilities['events'] = true
    ems.save!
    ```

### Proposed Fix

The capability update logic must be moved to execute after `super` and only when checking for the default connection or the AMQP connection.

```ruby
def verify_credentials(auth_type = nil, options = {})
  options[:service] ||= "Compute"
  ret = super
  
  # Logic to update the event capability is moved here to ensure it runs
  # after super() succeeds, covering both auth_type=nil and auth_type="amqp".
  if auth_type.nil? || auth_type.to_s == "amqp"
    capabilities["events"] = !!event_monitor_available?
        
    save! if changed?
  end
  
  return ret unless auth_type.nil?
  
  true
end
```

Wrapping the capability update in `if auth_type.nil? || auth_type.to_s == "amqp"` ensures that the capability is checked and set only when relevant. By positioning this block *before* the early exit check, we guarantee that the event capability is updated immediately upon successful AMQP verification.

-----

## ❓ Alternative Considerations / Questions

We propose the above change to automate the capability setting. However, we want to confirm the original design intent:

  * **Was the explicit early exit for non-`nil` `auth_types` intentional, requiring the `capabilities["events"]` to be set manually or via a different code path for security or architectural reasons?**

We are ready to submit a Pull Request (PR) with the proposed fix but are open to discussion if the original implementation was deliberate.

-----

## Labels

`bug`, `critical`, `openstack`, `events`, `amqp`

-----

### PR DESCRIPTION
**Pull request by agrare**
The OpenStack `verify_credentials` method has logic to check if the events monitor is available only if the requested `auth_type` is `nil`.

This was originally to prevent checking the events monitor when specific auth_type was requested to be checked.

In practice however there is always an auth_type passed in when called through `authentication_check_types` because:
```
types = authentications_to_validate if respond_to?(:authentications_to_validate)
```

This does have the downside of checking the event monitor on both default and (amqp|stf).

Fixes https://github.com/ManageIQ/manageiq-providers-openstack/issues/925

### CODE REVIEW

**Comment by agrare** [comment]
NOTE these specs are a little gross, going to try to clean them up a bit.

File: app/models/manageiq/providers/openstack/cloud_manager.rb [hunk 1]
```diff
@@ -480,10 +480,10 @@ def swift_service
 
   def verify_credentials(auth_type = nil, options = {})
     options[:service] ||= "Compute"
-    ret = super
-    return ret unless auth_type.nil?
 
-    capabilities["events"] = !!event_monitor_available?
+    super
+
+    capabilities["events"] = events_endpoint.present? && !!event_monitor_available?
```
Comment (agrare) [inline app/models/manageiq/providers/openstack/cloud_manager.rb]: TODO ideally `event_monitor_available?` would only be checked for a single `auth_type`.

This is complicated by the fact that `amqp` and `stf` have their own auth_type, but `ceilometer` doesn't.
So the logic should be something like:
`if we have an stf or amqp endpoint and that is the auth_type given, or if we have ceilometer and the auth_type is nil or default`

File: app/models/manageiq/providers/openstack/cloud_manager.rb [hunk 2]
```diff
@@ -550,6 +550,16 @@ def authentications_to_validate
     authentication_for_providers.collect(&:authentication_type) - [:ssh_keypair]
   end
 
+  def events_endpoint_roles
+    %w[amqp ceilometer stf].freeze
```
Comment (Fryguy) [inline app/models/manageiq/providers/openstack/cloud_manager.rb]: Why a method as opposed to a constant? will it be overridden by subclasses?

File: app/models/manageiq/providers/openstack/cloud_manager.rb (hunk 1 above)
Comment (Fryguy) [reply app/models/manageiq/providers/openstack/cloud_manager.rb]: Is that a TODO for this PR or for a future PR? If future, did you want to add a TODO comment in the source?

Comment (agrare) [reply app/models/manageiq/providers/openstack/cloud_manager.rb]: I want to fix this in this PR

File: app/models/manageiq/providers/openstack/cloud_manager.rb (hunk 2 above)
Comment (agrare) [reply app/models/manageiq/providers/openstack/cloud_manager.rb]: Originally I had more logic in this method, it could be a constant now

File: app/models/manageiq/providers/openstack/cloud_manager.rb (hunk 1 above)
Comment (agrare) [reply app/models/manageiq/providers/openstack/cloud_manager.rb]: Okay now we are only checking `event_monitor_avaiable?` if the auth_type requested is used for events

**Comment by agrare** [comment]
> NOTE these specs are a little gross, going to try to clean them up a bit.

I refactored the test contexts to cover more cases and read a little cleaner.  I separated the contexts for setting up the endpoints, if the auth is valid or not, and if the event monitor is available or not.

**Review by Fryguy — APPROVED** [review]

**Comment by Fryguy** [comment]
Backported to tal via merge of master into tal
